### ISSUE TITLE
后续开发功能点

### ISSUE THREAD

**Issue by ngot** [ngot/ngMD#2]
1.“/”结尾，直接认定为目录，不当做文件加载
2.添加对“XXX.json”文件require的支持，返回json解析后的对象
3.package.json不做直接解析，当做一个模块解析，并cache住解析后的对象

**Comment by ngot** [comment]
4.目录加载，也支持“XXX.json”文件的加载。package.json不存在，且index.js不存在，则尝试加载index.json；package.json存在且，配置main为“XXX.json”，则加载改“XXX.json”文件。

**Comment by hacke2** [comment]
赞一个

**Comment by ngot** [comment]
@hacke2 多谢支持，我再接再厉

**Comment by ngot** [comment]
1，2已完成。 3，4思考中

**Comment by ngot** [comment]
3，4使用场景太少，暂时就不支持了。先着手开发打包工具。
